Shopper_WebUI/Models/ResultMessage.cs
namespace Shopper_WebUI.Models
{
    public class ResultMessage
    {
        public string Title { get; set; }
        public string Message { get; set; }
        public string Css { get; set; } //warning,danger,success
    }
}

Shopper_WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Shopper_BLL.Abstract;
using Shopper_WebUI.Identity;
using Shopper_WebUI.Models;
using System.Net;
using System;
using IyzipayCore.Request;
using IyzipayCore.Model;
using Options = IyzipayCore.Options;
using Shopper_Entity;

namespace Shopper_WebUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<ApplicationUser> _userManager;
        private IOrderService _orderService;

        public CartController(ICartService cartService,UserManager<ApplicationUser> userManager,IOrderService orderService)
        {
            _orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            return View(new CartModel()
            {
                CartId=cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId=i.Id,
                    ProductId=i.Product.Id,
                    Name=i.Product.Name,
                    Price=i.Product.Price,
                    ImageUrl = i.Product.Images[0].ImageUrl,
                    Quantity=i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId,int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

		[HttpPost]
		public IActionResult DeleteFromCart(int productId)
		{
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId);
			return RedirectToAction("Index");
		}

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId=cart.Id,
                CartItems=cart.CartItems.Select(i=> new CartItemModel()
                {
                    CartItemId=i.Id,
                    ProductId=i.Product.Id,
                    Name=i.Product.Name,
                    Price=i.Product.Price,
                    ImageUrl = i.Product.Images[0].ImageUrl,
                    Quantity=i.Quantity
                }).ToList()
            };


            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            ModelState.Remove("CartModel");
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.Product.Id,
                        Name = i.Product.Name,
                        Price = (decimal)i.Product.Price,
                        ImageUrl = i.Product.Images[0].ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };

                //Ödeme
                var payment = PaymentProcess(model);

                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.Id.ToString());

                    return View("Success");
                }

                //Sipariş
            }

            return View(model);
        }

        private void ClearCart(string cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = EnumOrderState.Completed;
            order.PaymentTypes = EnumPaymentTypes.CreditCart;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.OrderNote = "Zil Çalma Bebek Uyuyor.";
            order.City = model.City;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.UserId = userId;

            foreach (var item in model.CartModel.CartItems)
            {
                var orderitem = new OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId
                };

                order.OrderItems.Add(orderitem);
            }

            _orderService.Create(order);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-A0FJYvo7hAleF1cAwNSYodVjELAj6EsB";
            options.SecretKey = "sandbox-OtWNn0GhKEKH0SVuwQcKYv1ZpEfDXCtD";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
            
            #region Payment
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth =model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvv;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = model.FirstName;
            buyer.Surname = model.LastName;
            buyer.GsmNumber = model.Phone;
            buyer.Email = model.Email;
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = model.City;
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;
            foreach (var item in model.CartModel.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.Name;
                basketItem.Category1 = "Telefon";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = (item.Price * item.Quantity).ToString().Split(",")[0];
                basketItems.Add(basketItem);
            }

            request.BasketItems = basketItems;


            return Payment.Create(request, options);
            #endregion

        }
    }
}

Shopper_WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Shopper_BLL.Abstract;
using Shopper_Entity;
using Shopper_WebUI.Models;

namespace Shopper_WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;

        public ShopController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        //products/telefon?page=2
        [Route("products/{category?}")]
        public IActionResult List(string category, int page=1)
        {
            const int pageSize = 3;
            return View(new ProductListModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems=_productService.GetCountByCategory(category),
                    CurrentPage=page,
                    CurrentCategory=category,
                    ItemsPerPage=pageSize
                },
                Products = _productService.GetProductsByCategory(category,page,pageSize)
            });
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();

            Product product = _productService.GetProductDetails(id.Value);

            if (product == null)
                return NotFound();

            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i=> i.Category).ToList(),
                Comments=product.Comments
            });
        }
    }
}

Shopper_WebUI/Views/Shared/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h1>Success</h1>

Shopper_WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="/modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="/modules/jquery/dist/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet" />
    <title>Shopper</title>
</head>
<body>
    <partial name="_navbar" />
    <div class="container mt-5 mb-5">
        @if(TempData["message"] !=null){
            <partial name="_resultMessage" model="@(TempData.Get<ResultMessage>("message"))" />
        }
        @RenderBody()
    </div>

   
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="~/modules/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>

Shopper_WebUI/Views/Shared/_PartialComments.cshtml
@using System.Security.Claims

@model List<CommentModel>

@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);    
}
<style>
    .btn-xs{--bs-btn-padding-y:.25rem;--bs-btn-padding-x:.5rem;--bs-btn-font-size:.75rem;}
</style>


@if(User.Identity.IsAuthenticated)
{
   <div class="row">
       <div class="col-md-12">
           <hr>
       </div>
   </div>

   <div class="row">
       <div class="col-md-12">
           <div class="input-group">
                <input type="text" id="new_comment_text" class="form-control" placeholder="yorumunuz.." />
                <span class="input-group-btn">
                    <button class="btn btn-success" type="button" onclick="doComment(this,'new_clicked',-1)">
                        <span class="fas fa-share"></span> Gönder
                    </button>
                </span>
           </div>
       </div>
   </div>
}

@foreach (var item in Model)
{
    <div class="d-flex">
        <div class="flex-grow-1 ms-12">
            <h6 class="col-md-12">@item.Username <small class="text-muted"><i>@item.CreateOn.ToString("dddd,dd MMMM yyyy")</i></small></h6>
            <span class="col-md-10" id="comment_text_@item.Id" contenteditable="false">
                @item.Text
            </span>
            @if (User.Identity.IsAuthenticated && item.UserId == userId)
            {
                <span class="col-md-2 float-end">
                    <button type="button" class="btn btn-warning btn-xs" data-edit-mode="false" onclick="doComment(this,'edit_clicked',@item.Id,'#comment_text_@item.Id')">
                        <span class="fas fa-edit fa-xs"></span>
                    </button>
                    <button type="button" class="btn btn-danger btn-xs" onclick="doComment(this,'delete_clicked',@item.Id)">
                        <span class="fas fa-trash-alt fa-xs"></span>
                    </button>
                </span>
            }            
        </div>

    </div>
}

Shopper_WebUI/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/Home/Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Shop" asp-action="List">Products</a>
                </li>
                @if(User.Identity.IsAuthenticated){
                    <li class="nav-item">
                        <a class="nav-link" href="/Cart/Index">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Orders</a>
                    </li>
                    if(User.IsInRole("admin")){
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="CreateProduct">Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/products">Admin Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="CreateCategory">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="CategoryList">Admin Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="UserList">Admin Users</a>
                        </li>
                    }
                  
                }
               
            </ul>
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0 float-end">
               
                @if(User.Identity.IsAuthenticated){
                    <li class="nav-item">
                        <a class="nav-link" href="/account/Manage">@User.Identity.Name</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/account/logout">Logout</a>
                    </li>
                  

                }
                else{
                    <li class="nav-item">
                        <a class="nav-link" href="/account/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/account/register">Register</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

Shopper_WebUI/Views/Shared/_products.cshtml
@model Product

<div class="col-md-4 mt-3">
    <div class="card">
        <img src="~/img/@Model.Images[0].ImageUrl" alt="@Model.Name" />

        <div class="card-body">
            <h4 class="card-title">
                <a href="#">@Model.Name</a>
            </h4>
            <small class="text-muted">
                <i class="fa-solid fa-turkish-lira-sign"></i>@Model.Price
            </small>
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-primary btn-sm">Details</a>
            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline">
                    <input type="hidden" name="productId" value="@Model.Id" />
                    <input type="hidden" name="quantity" value="1" />
                    <button type="submit" class="btn btn-outline-primary btn-sm ml-3">Add To Cart</button>
                </form>
            }
            
        </div>
    </div>
</div>

Shopper_WebUI/Views/Shared/_resultMessage.cshtml
@model ResultMessage

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-@Model.Css">
            <h4 class="alert-title">@Model.Title</h4>
            <p>@Model.Message</p>
        </div>
    </div>
</div>

Shopper_WebUI/Views/Shared/_slider.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/slider1.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/slider2.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/slider3.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>