Shopper_WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Shopper_BLL.Abstract;
using Shopper_WebUI.Identity;
using Shopper_WebUI.Models;
using System.Net;
using System;
using IyzipayCore.Request;
using IyzipayCore.Model;
using Options = IyzipayCore.Options;
using Shopper_Entity;

namespace Shopper_WebUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<ApplicationUser> _userManager;
        private IOrderService _orderService;

        public CartController(ICartService cartService,UserManager<ApplicationUser> userManager,IOrderService orderService)
        {
            _orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            return View(new CartModel()
            {
                CartId=cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId=i.Id,
                    ProductId=i.Product.Id,
                    Name=i.Product.Name,
                    Price=i.Product.Price,
                    ImageUrl = i.Product.Images[0].ImageUrl,
                    Quantity=i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId,int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

		[HttpPost]
		public IActionResult DeleteFromCart(int productId)
		{
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId);
			return RedirectToAction("Index");
		}

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId=cart.Id,
                CartItems=cart.CartItems.Select(i=> new CartItemModel()
                {
                    CartItemId=i.Id,
                    ProductId=i.Product.Id,
                    Name=i.Product.Name,
                    Price=i.Product.Price,
                    ImageUrl = i.Product.Images[0].ImageUrl,
                    Quantity=i.Quantity
                }).ToList()
            };


            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            ModelState.Remove("CartModel");
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.Product.Id,
                        Name = i.Product.Name,
                        Price = (decimal)i.Product.Price,
                        ImageUrl = i.Product.Images[0].ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };

                //Ödeme
                var payment = PaymentProcess(model);

                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.Id.ToString());

                    return View("Success");
                }

                //Sipariş
            }

            return View(model);
        }

        private void ClearCart(string cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = EnumOrderState.Completed;
            order.PaymentTypes = EnumPaymentTypes.CreditCart;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.OrderNote = "Zil Çalma Bebek Uyuyor.";
            order.City = model.City;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.UserId = userId;

            foreach (var item in model.CartModel.CartItems)
            {
                var orderitem = new OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId
                };

                order.OrderItems.Add(orderitem);
            }

            _orderService.Create(order);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-A0FJYvo7hAleF1cAwNSYodVjELAj6EsB";
            options.SecretKey = "sandbox-OtWNn0GhKEKH0SVuwQcKYv1ZpEfDXCtD";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
            
            #region Payment
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth =model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvv;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = model.FirstName;
            buyer.Surname = model.LastName;
            buyer.GsmNumber = model.Phone;
            buyer.Email = model.Email;
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = model.City;
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;
            foreach (var item in model.CartModel.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.Name;
                basketItem.Category1 = "Telefon";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = (item.Price * item.Quantity).ToString().Split(",")[0];
                basketItems.Add(basketItem);
            }

            request.BasketItems = basketItems;


            return Payment.Create(request, options);
            #endregion

        }
    }
}

Shopper_WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Shopper_BLL.Abstract;
using Shopper_Entity;
using Shopper_WebUI.Models;

namespace Shopper_WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;

        public ShopController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        //products/telefon?page=2
        [Route("products/{category?}")]
        public IActionResult List(string category, int page=1)
        {
            const int pageSize = 3;
            return View(new ProductListModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems=_productService.GetCountByCategory(category),
                    CurrentPage=page,
                    CurrentCategory=category,
                    ItemsPerPage=pageSize
                },
                Products = _productService.GetProductsByCategory(category,page,pageSize)
            });
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();

            Product product = _productService.GetProductDetails(id.Value);

            if (product == null)
                return NotFound();

            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i=> i.Category).ToList(),
                Comments=product.Comments
            });
        }
    }
}

Shopper_WebUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Shopper_BLL.Abstract;
using Shopper_WebUI.Models;

namespace Shopper_WebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            return View(new CategoryListViewModel()
            {
                SelectedCategory = RouteData.Values["category"]?.ToString(),
                Categories = _categoryService.GetAll()
            });
        }
    }
}

Shopper_WebUI/Views/Shop/Details.cshtml
@model ProductDetailsModel
@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12">
                <img src="~/img/@Model.Product.Images[0].ImageUrl" alt="@Model.Product.Name" class="fluid-img" id="imageBox" />
            </div>
        </div>
        <div class="row">
            @for (int i = 0; i < Model.Product.Images.Count; i++)
            {
                <div class="col-md-3">
                    <img src="~/img/@Model.Product.Images[i].ImageUrl" alt="@Model.Product.Name" class="img-fluid" style="display-block" onclick=myFunction(this) />
                </div>
            }
        </div>

    </div>
    <div class="col-md-9">
        <h1 class="mb-3">
            @Model.Product.Name
        </h1>
        <hr />
        @foreach (var item in Model.Categories)
        {
            <a href="#" class="btn btn-link p-0 mb-3">@item.Name</a>
        }

        <div class="mb-3">
            <h4 class="text-primary mb-3">
                @Model.Product.Price TL
            </h4>

            <form asp-controller="Cart" asp-action="AddToCart" method="post">
                <input type="hidden" name="productId" value="@Model.Product.Id" />
				<div class="row">
					<div class="col-md-3">
                         <button type="submit" class="btn btn-outline-primary">
                           <span class="fas fa-cart-plus"></span> Add To Cart</button>
                    </div>
					<div class="col-md-6">
                        <input type="number" name="quantity" class="form-control" value="1" min="1" step="1"/>
                    </div>
                </div>		
              
            </form>


        </div>
    </div>
</div>
<div class="row">
    <ul class="nav nav-tabs mt-2" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#comment" type="button" role="tab" aria-controls="home" aria-selected="true">Yorumlar</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#detail" type="button" role="tab" aria-controls="profile" aria-selected="false">Ürün Detay</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="comment" role="tabpanel" aria-labelledby="home-tab" data-product-id="@Model.Product.Id" data-url="@Url.Action(action:"ShowProductComments", controller:"Comment", new{id=Model.Product.Id})"> </div>
            @* <partial name="_PartialComments" for="@Model.Comments" />*@
            <div class="tab-pane fade" id="detail" role="tabpanel" aria-labelledby="profile-tab">@Html.Raw(Model.Product.Description)</div>

       
    </div>
</div>


<script src="~/js/comment.js" type="text/javascript"></script>

Shopper_WebUI/Views/Shop/List.cshtml
@model ProductListModel

<div class="row">
    <div class="col-md-3">
       @await Component.InvokeAsync("CategoryList")
    </div>
    <div class="col-md-9">       
        <div class="row">
            @foreach (var item in Model.Products)
            {
                <partial name="_products" for="@item" />
            }
        </div>
        <div page-model="@Model.PageInfo"></div>
    </div>
</div>